version: '3'
services:
  api_db:
    build: ./db
    image: api_db
    container_name: api_db
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
    ports:
      - '5432:5432'
